# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib blaze, .registration = TRUE
NULL

#' Check the base type of `value` against `expected`, returning `NULL` on a
#' match or a message describing the mismatch.
#' @noRd
blaze_check_base <- function(value, expected) .Call(wrap__blaze_check_base, value, expected)

# nolint end
