# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib blaze, .registration = TRUE
NULL

#' Check the base type of `value` against `expected`, returning `NULL` on a
#' match or a message describing the mismatch.
#' @noRd
blaze_check_base <- function(value, expected) .Call(wrap__blaze_check_base, value, expected)

#' Check the length of `value` against `expected` (empty means no constraint),
#' returning `NULL` on a match or a message describing the mismatch.
#' @noRd
blaze_check_length <- function(value, expected) .Call(wrap__blaze_check_length, value, expected)

# nolint end
